# Generated by Django 5.1.7 on 2025-04-25 06:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('analysis', '0001_initial'), ('analysis', '0002_case_casereaction'), ('analysis', '0003_remove_case_drug_casedrug'), ('analysis', '0004_rename_drug_druglist_rename_reaction_reactionlist_and_more'), ('analysis', '0005_drug_reaction'), ('analysis', '0006_create_demo_and_outcome_models_and_rename_case_faers_id_fields'), ('analysis', '0007_drugname_reactionname_alter_demo_age_cod_and_more'), ('analysis', '0008_query_year_end_query_year_start_and_more'), ('analysis', '0009_demo_valid_sex_choice_demo_valid_age_cod_choice_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faers_primaryid', models.BigIntegerField(unique=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)])),
                ('quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('faers_caseid', models.BigIntegerField(default=-1)),
            ],
            options={
                'ordering': ['year', 'quarter'],
            },
        ),
        migrations.CreateModel(
            name='DrugName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, validators=[django.core.validators.MaxLengthValidator(255)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, validators=[django.core.validators.MaxLengthValidator(255)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.drugname')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.reactionname')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter_start', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('quarter_end', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('x_values', models.JSONField(default=list)),
                ('y_values', models.JSONField(default=list)),
                ('drugs', models.ManyToManyField(to='analysis.drugname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(to='analysis.reactionname')),
                ('year_end', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2025)])),
                ('year_start', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2025)])),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quarter_start__lte', models.F('quarter_end'))), name='quarter_start_lte_quarter_end')],
            },
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_dt_num', models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)])),
                ('age_cod', models.TextField(choices=[('DEC', 'Decade'), ('YR', 'Year'), ('MON', 'Month'), ('WK', 'Week'), ('DY', 'Day'), ('HR', 'Hour')], null=True, validators=[django.core.validators.MaxLengthValidator(5)])),
                ('sex', models.TextField(choices=[('UNK', 'Unknown'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified'), ('NS', 'Not Specified')], null=True, validators=[django.core.validators.MaxLengthValidator(5)])),
                ('wt', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('wt_cod', models.TextField(choices=[('KG', 'Kilograms'), ('LBS', 'Pounds'), ('GMS', 'Grams')], null=True, validators=[django.core.validators.MaxLengthValidator(5)])),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('sex__in', ['UNK', 'M', 'F', 'U', 'NS'])), name='valid_sex_choice'), models.CheckConstraint(condition=models.Q(('age_cod__in', ['DEC', 'YR', 'MON', 'WK', 'DY', 'HR'])), name='valid_age_cod_choice'), models.CheckConstraint(condition=models.Q(('wt_cod__in', ['KG', 'LBS', 'GMS'])), name='valid_wt_cod_choice')],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outc_cod', models.TextField(choices=[('DE', 'Death'), ('LT', 'Life-Threatening'), ('HO', 'Hospitalization - Initial or Prolonged'), ('DS', 'Disability'), ('CA', 'Congenital Anomaly'), ('RI', 'Required Intervention to Prevent Permanent Impairment/Damage'), ('OT', 'Other Serious (Important Medical Event)')], null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('outc_cod__in', ['DE', 'LT', 'HO', 'DS', 'CA', 'RI', 'OT'])), name='valid_outc_cod_choice')],
            },
        ),
    ]
