# Generated by Django 5.1.7 on 2025-03-24 23:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faers_primary_id', models.BigIntegerField(unique=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)])),
                ('quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.drug')),
            ],
            options={
                'ordering': ['year', 'quarter'],
            },
        ),
        migrations.CreateModel(
            name='CaseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.reaction')),
            ],
        ),
    ]
