# Generated by Django 5.1.7 on 2025-03-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_case_drug_casedrug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drug',
            new_name='DrugList',
        ),
        migrations.RenameModel(
            old_name='Reaction',
            new_name='ReactionList',
        ),
        migrations.RemoveField(
            model_name='casereaction',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casereaction',
            name='reaction',
        ),
        migrations.DeleteModel(
            name='CaseDrug',
        ),
        migrations.DeleteModel(
            name='CaseReaction',
        ),
    ]
