# Generated by Django 5.1.7 on 2025-03-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_rename_drug_druglist_rename_reaction_reactionlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.druglist')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.reactionlist')),
            ],
        ),
    ]
