# Generated by Django 5.1.7 on 2025-03-27 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_drug_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='faers_primary_id',
            new_name='faers_primaryid',
        ),
        migrations.AddField(
            model_name='case',
            name='faers_caseid',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_dt_num', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(130)])),
                ('age_cod', models.CharField(choices=[('DEC', 'Decade'), ('YR', 'Year'), ('MON', 'Month'), ('WK', 'Week'), ('DY', 'Day'), ('HR', 'Hour')], max_length=5, null=True)),
                ('sex', models.CharField(choices=[('UNK', 'Unknown'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified'), ('NS', 'Not Specified')], max_length=5, null=True)),
                ('wt', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('wt_cod', models.CharField(choices=[('KG', 'Kilograms'), ('LBS', 'Pounds'), ('GMS', 'Grams')], max_length=5, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outc_cod', models.CharField(choices=[('DE', 'Death'), ('LT', 'Life-Threatening'), ('HO', 'Hospitalization - Initial or Prolonged'), ('DS', 'Disability'), ('CA', 'Congenital Anomaly'), ('RI', 'Required Intervention to Prevent Permanent Impairment/Damage'), ('OT', 'Other Serious (Important Medical Event)')], max_length=5, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
            ],
        ),
    ]
