# Generated by Django 5.1.7 on 2025-03-28 12:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_create_demo_and_outcome_models_and_rename_case_faers_id_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, validators=[django.core.validators.MaxLengthValidator(255)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, validators=[django.core.validators.MaxLengthValidator(255)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='demo',
            name='age_cod',
            field=models.TextField(choices=[('DEC', 'Decade'), ('YR', 'Year'), ('MON', 'Month'), ('WK', 'Week'), ('DY', 'Day'), ('HR', 'Hour')], null=True, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='event_dt_num',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='sex',
            field=models.TextField(choices=[('UNK', 'Unknown'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified'), ('NS', 'Not Specified')], null=True, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='wt_cod',
            field=models.TextField(choices=[('KG', 'Kilograms'), ('LBS', 'Pounds'), ('GMS', 'Grams')], null=True, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outc_cod',
            field=models.TextField(choices=[('DE', 'Death'), ('LT', 'Life-Threatening'), ('HO', 'Hospitalization - Initial or Prolonged'), ('DS', 'Disability'), ('CA', 'Congenital Anomaly'), ('RI', 'Required Intervention to Prevent Permanent Impairment/Damage'), ('OT', 'Other Serious (Important Medical Event)')], null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.drugname'),
        ),
        migrations.AlterField(
            model_name='query',
            name='drugs',
            field=models.ManyToManyField(to='analysis.drugname'),
        ),
        migrations.AlterField(
            model_name='query',
            name='reactions',
            field=models.ManyToManyField(to='analysis.reactionname'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.reactionname'),
        ),
        migrations.DeleteModel(
            name='DrugList',
        ),
        migrations.DeleteModel(
            name='ReactionList',
        ),
    ]
