# Generated by Django 5.1.7 on 2025-04-27 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_squashed_0009_demo_valid_sex_choice_demo_valid_age_cod_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='faers_caseid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='demo',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='age_cod',
            field=models.TextField(blank=True, choices=[('DEC', 'Decade'), ('YR', 'Year'), ('MON', 'Month'), ('WK', 'Week'), ('DY', 'Day'), ('HR', 'Hour')], null=True, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='event_dt_num',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='sex',
            field=models.TextField(blank=True, choices=[('UNK', 'Unknown'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified'), ('NS', 'Not Specified')], null=True, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='wt',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='demo',
            name='wt_cod',
            field=models.TextField(blank=True, choices=[('KG', 'Kilograms'), ('LBS', 'Pounds'), ('GMS', 'Grams')], null=True, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outc_cod',
            field=models.TextField(choices=[('DE', 'Death'), ('LT', 'Life-Threatening'), ('HO', 'Hospitalization - Initial or Prolonged'), ('DS', 'Disability'), ('CA', 'Congenital Anomaly'), ('RI', 'Required Intervention to Prevent Permanent Impairment/Damage'), ('OT', 'Other Serious (Important Medical Event)')], null=True, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='query',
            name='year_end',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='query',
            name='year_start',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['year', 'quarter'], name='analysis_ca_year_4d8f93_idx'),
        ),
        migrations.AddConstraint(
            model_name='demo',
            constraint=models.CheckConstraint(condition=models.Q(('age_cod__isnull', True), models.Q(('age_cod', 'DEC'), ('age__lte', 12)), models.Q(('age_cod', 'YR'), ('age__lte', 120)), models.Q(('age_cod', 'MON'), ('age__lte', 1440)), models.Q(('age_cod', 'WK'), ('age__lte', 6240)), models.Q(('age_cod', 'DY'), ('age__lte', 43800)), models.Q(('age_cod', 'HR'), ('age__lte', 1051200)), _connector='OR'), name='valid_age_for_age_code'),
        ),
    ]
