# Generated by Django 5.2.1 on 2025-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_alter_case_faers_caseid_alter_demo_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='x_values',
            new_name='ror_lower',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='y_values',
            new_name='ror_upper',
        ),
        migrations.AddField(
            model_name='query',
            name='ror_values',
            field=models.JSONField(default=list),
        ),
    ]
