# Generated by Django 5.2.1 on 2025-08-26 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_rename_x_values_query_ror_lower_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='query',
            name='quarter_start_lte_quarter_end',
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.CheckConstraint(condition=models.Q(('year_start__lte', models.F('year_end'))), name='year_start_lte_year_end'),
        ),
    ]
