# Generated by Django 5.2.1 on 2025-10-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='ror_lower',
        ),
        migrations.RemoveField(
            model_name='query',
            name='ror_upper',
        ),
        migrations.RemoveField(
            model_name='query',
            name='ror_values',
        ),
    ]
