# Generated by Django 5.2.1 on 2025-10-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_remove_query_ror_lower_remove_query_ror_upper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='case',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='case',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='case',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='reaction',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
