# Generated by Django 5.1.7 on 2025-03-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_case_casereaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='drug',
        ),
        migrations.CreateModel(
            name='CaseDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.case')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.drug')),
            ],
        ),
    ]
