# Generated by Django 5.1.7 on 2025-08-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google account ID for OAuth2 authentication.', max_length=255, null=True, unique=True),
        ),
    ]
